from datetime import datetime
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()


class User(db.Model):
    """User model for authentication and profile management."""

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), unique=True, nullable=False, index=True)
    password_hash = db.Column(db.String(255), nullable=False)
    first_name = db.Column(db.String(50), nullable=False)
    last_name = db.Column(db.String(50), nullable=False)
    user_type = db.Column(db.String(20), nullable=False, default='individual')  # individual, therapist, admin
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    is_active = db.Column(db.Boolean, default=True)

    # Relationships
    mood_entries = db.relationship('MoodEntry', backref='user', lazy=True, cascade='all, delete-orphan')
    therapy_sessions = db.relationship('TherapySession', foreign_keys='TherapySession.user_id', backref='user', lazy=True, cascade='all, delete-orphan')
    self_care_plans = db.relationship('SelfCarePlan', backref='user', lazy=True, cascade='all, delete-orphan')

    def set_password(self, password):
        """Hash and set the user password."""
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        """Check if the provided password matches the hash."""
        return check_password_hash(self.password_hash, password)

    def to_dict(self):
        """Convert user object to dictionary."""
        return {
            'id': self.id,
            'email': self.email,
            'first_name': self.first_name,
            'last_name': self.last_name,
            'user_type': self.user_type,
            'created_at': self.created_at.isoformat(),
            'is_active': self.is_active
        }


class MoodEntry(db.Model):
    """Mood tracking entries with emotions and context."""

    __tablename__ = 'mood_entries'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    mood_score = db.Column(db.Integer, nullable=False)  # 1-10 scale
    emotions = db.Column(db.JSON)  # List of emotions (e.g., ["anxious", "happy"])
    notes = db.Column(db.Text)
    activities = db.Column(db.JSON)  # List of activities
    triggers = db.Column(db.JSON)  # List of potential triggers
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def to_dict(self):
        """Convert mood entry to dictionary."""
        return {
            'id': self.id,
            'user_id': self.user_id,
            'mood_score': self.mood_score,
            'emotions': self.emotions,
            'notes': self.notes,
            'activities': self.activities,
            'triggers': self.triggers,
            'created_at': self.created_at.isoformat()
        }


class TherapySession(db.Model):
    """Virtual therapy session scheduling and management."""

    __tablename__ = 'therapy_sessions'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    therapist_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    session_type = db.Column(db.String(50), nullable=False)  # virtual, in-person, chat
    scheduled_at = db.Column(db.DateTime, nullable=False)
    duration_minutes = db.Column(db.Integer, default=60)
    status = db.Column(db.String(20), default='scheduled')  # scheduled, completed, cancelled
    notes = db.Column(db.Text)
    session_summary = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    therapist = db.relationship('User', foreign_keys=[therapist_id], backref='therapist_sessions')

    def to_dict(self):
        """Convert therapy session to dictionary."""
        return {
            'id': self.id,
            'user_id': self.user_id,
            'therapist_id': self.therapist_id,
            'session_type': self.session_type,
            'scheduled_at': self.scheduled_at.isoformat(),
            'duration_minutes': self.duration_minutes,
            'status': self.status,
            'notes': self.notes,
            'session_summary': self.session_summary,
            'created_at': self.created_at.isoformat()
        }


class SelfCarePlan(db.Model):
    """Personalized self-care plans generated by AI."""

    __tablename__ = 'self_care_plans'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    title = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text)
    recommendations = db.Column(db.JSON)  # List of recommendation items
    goals = db.Column(db.JSON)  # List of goals
    duration_weeks = db.Column(db.Integer, default=4)
    is_active = db.Column(db.Boolean, default=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def to_dict(self):
        """Convert self-care plan to dictionary."""
        return {
            'id': self.id,
            'user_id': self.user_id,
            'title': self.title,
            'description': self.description,
            'recommendations': self.recommendations,
            'goals': self.goals,
            'duration_weeks': self.duration_weeks,
            'is_active': self.is_active,
            'created_at': self.created_at.isoformat()
        }


class AIInsight(db.Model):
    """AI-generated insights and recommendations."""

    __tablename__ = 'ai_insights'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    insight_type = db.Column(db.String(50), nullable=False)  # mood_pattern, recommendation, alert
    content = db.Column(db.Text, nullable=False)
    confidence_score = db.Column(db.Float)  # 0.0 to 1.0
    insight_metadata = db.Column(db.JSON)
    is_read = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    user = db.relationship('User', backref='ai_insights')

    def to_dict(self):
        """Convert AI insight to dictionary."""
        return {
            'id': self.id,
            'user_id': self.user_id,
            'insight_type': self.insight_type,
            'content': self.content,
            'confidence_score': self.confidence_score,
            'metadata': self.insight_metadata,
            'is_read': self.is_read,
            'created_at': self.created_at.isoformat()
        }
